#!/bin/sh

set -e

VLAN_LIST="`sed -n '/^iface vlan/ s/iface \(vlan[0-9]\) .*/\1/ p' /etc/network/interfaces `"

case "$2" in
    up)
        for vlan in $VLAN_LIST ; do
            /sbin/ifup $vlan
        done
        ;;
    down)
        for vlan in $VLAN_LIST ; do
            /sbin/ifdown $vlan
        done
        ;;
esac
