#!/bin/bash

options="--logdest syslog"
if [ "$PUPPET_BOOT" = "true" ]; then
    options="--logdest console --tags boot --color false"
fi

/usr/bin/puppet apply $options /etc/puppet/manifests/site.pp
puppet_error_level=$?

if [ $puppet_error_level != 0 ]; then
    echo "Errors during puppet configuration, check syslog"
    exit $puppet_error_level
fi
