#!/bin/bash

options="--logdest syslog"
if [ "$1" = "boot" ]; then
    exec > /tmp/launch-puppet-boot.log 2>&1

    options="--logdest console --tags boot --color false"

    if [  ! -f "/var/etc/puppet/manifests/config.pp" ]; then
        mkdir -p "/var/etc/puppet/manifests"
        echo "Restore stored configuration"
        cp "/boot/config.pp" "/var/etc/puppet/manifests/config.pp"
        chown www-data "/var/etc/puppet/manifests/config.pp"
    fi
fi

/usr/bin/puppet --debug $options /etc/puppet/manifests/site.pp
puppet_error_level=$?

if [ "$1" = "boot" ]; then
    if [ $puppet_error_level != 0 ]; then
        cat /tmp/launch-puppet-boot.log
        sleep 30
    fi
fi

