#!/bin/bash

capture=true
playback=false

logger -i -t "amixerconf" "Configure sound card mixer for $1"

case $1 in
    playback)
        capture=false
        playback=true
        ;;
    duplex)
        capture=true
        playback=true
        ;;
    capture)
        capture=true
        playback=false
        ;;
    default)
        echo "Usage amixerconf [capture|playback|duplex]"
        exit 1
        ;;
esac

if [ $capture = "true" ]; then
    if amixer controls | grep -q 'Input Source'; then
    # Looks like a Realtek ALC887 mixer
    # no capture switch on Line but an "Input Source" control
        amixer -- sset 'Input Source' 'Line'
        amixer -- sset 'Capture' 0dB cap
    elif amixer controls | grep -q 'ADC Volume'; then
        # Looks like a M-Audio Delta 44 / 1010
        max_index=`amixer controls | grep 'ADC Volume' | sed -n 's/.*index=\([0-9]\)/\1/p' | sort | tail -1`
        for (( index=0; index<=$max_index; index++ )) do
            amixer -- sset ADC,$index 0dB unmute
            amixer -- sset DAC,$index 0dB unmute

            if [ $playback != "true" ]; then
              # Loopback inputs
              amixer -- sset 'H/W',$index "H/W In $index"
            fi
        done
    elif [ `cat /proc/asound/card0/id` = "Juli" ]; then
        # It is a Juli@ card
        # Inputs are always ON and their gain cannot be controled
        if [ $playback != "true" ]; then
        # Loopback inputs
            amixer -- sset 'H/W',0 'H/W In 0'
            amixer -- sset 'H/W',1 'H/W In 1'
        fi
    elif [ `cat /proc/asound/card0/id` = "Live" ];then
    #It is a SoundBlaster Live!
        amixer -- sset 'AC97' cap 0dB
        amixer -- sset 'Line' cap
    else
        amixer -- sset 'Line' cap
    fi
fi

amixer -- sset 'Master' 100% unmute
amixer -- sset 'PCM' 100% unmute

if [ $playback = "true" ]; then
    if amixer controls | grep -q 'H/W'; then
      # TODO support 4 channels  
      amixer -- sset 'H/W',0 'PCM Out'
      amixer -- sset 'H/W',1 'PCM Out'
    fi
fi
